server:
  port: 8080

spring:
  application:

    name: eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      #http://localhost:8080/eureka/eureka
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: 127.0.0.1:8080
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000